# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recontent < Formula
  desc ""
  homepage "https://github.com/recontentapp/cli"
  version "0.1.0"

  on_macos do
    url "https://github.com/recontentapp/cli/releases/download/0.1.0/cli_0.1.0_Darwin_all.tar.gz"
    sha256 "5a2f00b351c46726fb3d2c8d2069de0f9dd92cc29da6cc8c9be9445661563fac"

    def install
      bin.install "cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/recontentapp/cli/releases/download/0.1.0/cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "6ec9ed4d137d00dd415012200ed99e16d471d55642cffda63bf12673f923f203"

      def install
        bin.install "recontent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/recontentapp/cli/releases/download/0.1.0/cli_0.1.0_Linux_arm64.tar.gz"
      sha256 "36673846701721a676699baa0ab345bc83bbb42bffc85d775c88c6f98f421870"

      def install
        bin.install "recontent"
      end
    end
  end
end
